logging:
  file: ${user.home}/logs/demo.log
  level:
    com:
      passiontec: debug
    org:
      springframework: info

job:
  server: localhost:8080/client/getTask

spring:
  profiles:
    active: local
---
spring:
  profiles: local
  quartz:
    threadCount: 5
  redis:
    address: 127.0.0.1:6379
    password:
    timeout : 10000
  kafka:
    address: 127.0.0.1:2181

---
spring:
  profiles: develop
---
spring:
  profiles: test
