logging:
  file: ${user.home}/logs/demo.log
  level:
    com:
      passiontec: debug
    org:
      springframework: info

server:
  port: 6666
  servlet-path: /
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

spring:
  profiles: local
  quartz:
    group:
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qrtz?useUnicode=true&characterEncoding=utf8
    username: root
    password: ok
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT 1
    test-while-idle: true
  redis:
    host : 127.0.0.1
    port : 6379
    timeout : 10000
    jobChannel: quartz_job_channel
    jobStatusChannel: quartz_job_status_channel
  kafka:
    address: 127.0.0.1:2181
    jobTopic: quartz_job_topic
    jobStatusTopic: quartz_job_status_topic
  mail:
    host: smtp.163.com
    username: 286352250@163.com
    password: 用户密码
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
---
spring:
  profiles: develop
---
spring:
  profiles: test
---
spring:
  profiles:
    active: local
