logging:
  file: ${user.home}/logs/demo.log
  level:
    com:
      passiontec: debug
    org:
      springframework: info

server:
  port: 8080
  servlet-path: /
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qrtz?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT 1
    test-while-idle: true
  redis:
    host : 127.0.0.1
    port : 6379
    timeout : 10000
    jobChannel: quartz_job_channel
    jobStatusChannel: quartz_job_status_channel
---
spring:
  profiles: develop
---
spring:
  profiles: test

