logging:
  file: ${user.home}/logs/demo.log
  level:
    com:
      passiontec: debug
    org:
      springframework: info

quartz:
  group: demo

spring:
  profiles:
    active: local
---
spring:
  profiles: local
---
spring:
  profiles: develop
---
spring:
  profiles: test

