logging:
  file: ${user.home}/logs/demo.log
  level:
    com:
      passiontec: debug
    org:
      springframework: info

job:
  server: localhost:8080/client/getTask

spring:
  profiles:
    active: local
---
spring:
  profiles: local
  quartz:
    threadCount: 5
    redisAddress: 127.0.0.1:6379
    redisPassWord:
    jobChannel: quartz_job_channel
    jobStatusChannel: quartz_job_status_channel
   redis:
      host : 127.0.0.1
      port : 6379
      timeout : 10000
      jobChannel: quartz_job_channel
      jobStatusChannel: quartz_job_status_channel
---
spring:
  profiles: develop
---
spring:
  profiles: test
